"""AI Flashcard Generation request, response, streaming event, and LangGraph state models."""

from typing import Literal

from pydantic import Field

from app.models.common import CamelModel
from app.models.set import FlashcardSet


class AIGenerationRequest(CamelModel):
    """Payload submitted from frontend to initiate AI flashcard generation."""

    prompt: str | None = Field(
        default=None,
        description="Optional or specific user focus prompt describing what flashcards to generate.",
    )
    document_ids: list[str] = Field(
        default_factory=list,
        description="List of Document IDs or Drive file IDs to strictly ground the cards on.",
    )
    raw_text: str | None = Field(
        default=None,
        description="Optional raw lecture notes or textbook markdown pasted directly.",
    )
    folder_id: str | None = Field(
        default=None,
        description="Destination folder ID where the created Set will reside. None indicates root workspace.",
    )
    set_name: str | None = Field(
        default=None,
        max_length=150,
        description="Optional custom name for the created set. Auto-generated by AI if omitted.",
    )
    set_description: str | None = Field(
        default=None,
        max_length=1000,
        description="Optional description for the created set.",
    )
    focus_mode: str | None = Field(
        default=None,
        description="Optional focus style (e.g. 'exhaustive', 'definitions', 'mechanisms', 'cases').",
    )


class AIGenerationEvent(CamelModel):
    """Server-Sent Event (SSE) payload dispatched during multi-agent graph execution."""

    stage: Literal[
        "init",
        "planning",
        "generating",
        "reviewing",
        "refining",
        "persisting",
        "completed",
        "error",
    ] = Field(..., description="Current lifecycle phase of the multi-agent graph.")
    progress: int = Field(
        ..., ge=0, le=100, description="Approximate percent completion (0 to 100)."
    )
    message: str = Field(..., description="Human-readable status summary for UI progress display.")
    card_count: int = Field(default=0, ge=0, description="Current tally of synthesized cards.")
    set_id: str | None = Field(default=None, description="Created set ID once persisted.")
    set_name: str | None = Field(default=None, description="Final title of the flashcard set.")
    error: str | None = Field(default=None, description="Error message if generation failed.")


class CurriculumTopic(CamelModel):
    """Decomposed syllabus/module topic chunk generated during the Planning phase."""

    topic_id: str = Field(..., description="Unique slug or index for the topic.")
    title: str = Field(..., description="Descriptive title of the section/module.")
    summary: str = Field(..., description="Brief summary of concepts contained.")
    source_reference_hint: str | None = Field(
        default=None,
        description="Associated slide range, chapter, or document page (e.g., 'Slides 12-25').",
    )
    key_concepts: list[str] = Field(
        default_factory=list, description="List of atomic terms, formulas, or mechanisms to cover."
    )


class GeneratedCardItem(CamelModel):
    """Individual synthesized flashcard with atomic Q&A and citation metadata."""

    front: str = Field(
        ..., min_length=1, description="Front face (supports Markdown and LaTeX math)."
    )
    back: str = Field(
        ..., min_length=1, description="Back face (supports Markdown and LaTeX math)."
    )
    document_id: str | None = Field(
        default=None, description="ID of source document if grounded."
    )
    document_name: str | None = Field(
        default=None, description="Cached filename of source document for citation display."
    )
    page_number: int | None = Field(
        default=None, ge=1, description="1-indexed slide or page number."
    )
    tags: list[str] = Field(
        default_factory=list, description="Categorical tags for this card."
    )
    grounding_evidence: str | None = Field(
        default=None,
        description="Exact 1-2 sentence verbatim evidence excerpt or formula from the document verifying this card.",
    )


class ReviewAuditResult(CamelModel):
    """Audit report generated by the Reviewer Node evaluating quality and completeness."""

    is_approved: bool = Field(
        ..., description="True if cards satisfy completeness, grounding, and quality standards."
    )
    quality_score: int = Field(
        ..., ge=0, le=100, description="Overall quality & coverage score out of 100."
    )
    missing_topics: list[str] = Field(
        default_factory=list,
        description="Specific topics, mechanisms, or slides that were skipped and need cards.",
    )
    critique_notes: str = Field(
        default="", description="Constructive feedback for refinement."
    )


class GenerationResult(CamelModel):
    """Final result payload returned upon successful generation."""

    set: FlashcardSet
    cards_created_count: int
    quality_score: int
    iterations_run: int
